### ISSUE TITLE
make standalone npm package please

### ISSUE THREAD

**Issue by raypulver** [AztecProtocol/huff#3]
Huff enthusiast here, we would really like to see AZTEC publish a npm package for a standalone installation of the Huff assembler. As far as I know the only way to install is to clone the AztecProtocol repo (see https://bitbucket.org/raypulver/huff-standalone)

The npm package should maintain the latest version of the Huff assembler and export the same object that the huff package in the AZTEC repo exports that we're used to.

**Comment by d1ll0n** [comment]
Huff has been added to npm under the package name `@aztec/huff`.
